// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UptimeMonitor.Web.Api.Data;

#nullable disable

namespace UptimeMonitor.Web.Api.Migrations
{
    [DbContext(typeof(MonitorDbContext))]
    [Migration("20250401065834_SetTimeoutDefaults")]
    partial class SetTimeoutDefaults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MonitorConfigurationStatusPageMonitorGroup", b =>
                {
                    b.Property<int>("MonitorsId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusPageMonitorGroupId")
                        .HasColumnType("integer");

                    b.HasKey("MonitorsId", "StatusPageMonitorGroupId");

                    b.HasIndex("StatusPageMonitorGroupId");

                    b.ToTable("MonitorConfigurationStatusPageMonitorGroup");
                });

            modelBuilder.Entity("UptimeMonitor.Core.Domain.Monitors.MonitorConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Timeout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MonitorConfigurations");
                });

            modelBuilder.Entity("UptimeMonitor.Core.Domain.StatusPages.StatusPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StatusPages");
                });

            modelBuilder.Entity("UptimeMonitor.Core.Domain.StatusPages.StatusPageMonitorGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StatusPageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatusPageId");

                    b.ToTable("StatusPageMonitorGroup");
                });

            modelBuilder.Entity("UptimeMonitor.Core.Domain.Workers.WorkerConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<int>("ConfigUpdateInterval")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastCheckIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WorkerConfigurations");
                });

            modelBuilder.Entity("UptimeMonitor.Web.Api.Data.MonitorResultEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MonitorConfigurationId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("ResponseTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkerConfigurationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MonitorConfigurationId");

                    b.HasIndex("WorkerConfigurationId");

                    b.ToTable("MonitorResults");
                });

            modelBuilder.Entity("MonitorConfigurationStatusPageMonitorGroup", b =>
                {
                    b.HasOne("UptimeMonitor.Core.Domain.Monitors.MonitorConfiguration", null)
                        .WithMany()
                        .HasForeignKey("MonitorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UptimeMonitor.Core.Domain.StatusPages.StatusPageMonitorGroup", null)
                        .WithMany()
                        .HasForeignKey("StatusPageMonitorGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UptimeMonitor.Core.Domain.StatusPages.StatusPageMonitorGroup", b =>
                {
                    b.HasOne("UptimeMonitor.Core.Domain.StatusPages.StatusPage", null)
                        .WithMany("MonitorGroups")
                        .HasForeignKey("StatusPageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UptimeMonitor.Web.Api.Data.MonitorResultEntry", b =>
                {
                    b.HasOne("UptimeMonitor.Core.Domain.Monitors.MonitorConfiguration", null)
                        .WithMany()
                        .HasForeignKey("MonitorConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UptimeMonitor.Core.Domain.Workers.WorkerConfiguration", null)
                        .WithMany()
                        .HasForeignKey("WorkerConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UptimeMonitor.Core.Domain.StatusPages.StatusPage", b =>
                {
                    b.Navigation("MonitorGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
