name: Lint

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/**"

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  dotnet-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Dotnet Format
      run: dotnet format UptimeMonitor.sln --verify-no-changes --verbosity diagnostic
